version: '3.8'

services:
  postgres:
    container_name: nossa-cidade
    image: postgis/postgis:17-3.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nossa_cidade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
